name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Build project and assemble APKs in a single Gradle invocation
      - name: Build project
        run: ./gradlew build --configuration-cache --parallel --build-cache

      # Upload Artifact Build
      - name: Upload Debug Apk
        uses: actions/upload-artifact@v6
        with:
          name: apk-debug.zip
          path: app/build/outputs/apk/debug/app-debug.apk

      # Upload Artifact Build
      - name: Upload Release Apk
        uses: actions/upload-artifact@v6
        with:
          name: apk-release.zip
          path: app/build/outputs/apk/release/app-release-unsigned.apk
